# Generated by Django 3.1.1 on 2020-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='CLIENT NAME', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.CharField(default='M/D/Y', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='portfolio.Category'),
        ),
    ]
